version: "2"
services:

    webserver:
      image: nginx:alpine
      container_name: nginx
      working_dir: /docker
      environment:
        - TZ=Europe/Berlin
      volumes:
        - ../${PROJECTDIR}/:/docker
        - ./nginx/${PROJECTDIR}.${BRANCH}.conf:/etc/nginx/conf.d/default.conf
      links:
        - php-fpm
        - mysql
        - redis
        - memcached
        - mailhog
      ulimits:
        memlock:
          soft: -1
          hard: -1
      mem_limit: 512m
      ports:
       - "80:80"
       - "8080:8080"

    php-fpm:
      build:
        context: php-fpm
        dockerfile: ../php-fpm/Dockerfile${PHPVERSION}
      container_name: php
      working_dir: /docker/
      environment:
        - TZ=Europe/Berlin
        - PHP_IDE_CONFIG=serverName=127.0.0.1
      volumes:
        - ../${PROJECTDIR}/:/docker
        - ./php-fpm/php-ini-overrides.ini:/etc/php/${PHPVERSION}/fpm/conf.d/99-overrides.ini
      ulimits:
        memlock:
          soft: -1
          hard: -1
      mem_limit: 2g

    mysql:
      image: mysql:5.6
      container_name: mysql
      working_dir: /docker
      environment:
        - TZ=Europe/Berlin
        - MYSQL_ROOT_PASSWORD=root
      volumes:
        - ./.data/sql/:/var/lib/mysql
      ulimits:
        memlock:
          soft: -1
          hard: -1
      mem_limit: 1g
      ports:
        - "3306:3306"

    redis:
      image: redis:alpine
      container_name: redis
      ulimits:
        memlock:
          soft: -1
          hard: -1
      mem_limit: 512m

    memcached:
      image: memcached:alpine
      container_name: memcached
      ulimits:
        memlock:
          soft: -1
          hard: -1
      mem_limit: 256m

    mailhog:
      image: mailhog/mailhog:v1.0.0
      container_name: mailhog
      ulimits:
        memlock:
          soft: -1
          hard: -1
      mem_limit: 256m
      ports:
      - "1025:1025"
      - "8025:8025"